services:
  postgres14:
    image: postgres:14
    volumes:
      - "pgdata:/var/lib/postgresql/data"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: taxonomy_db

  postgres16:
    image: postgres:16
    volumes:
      - "pgdata:/var/lib/postgresql/data"
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: taxonomy_db

volumes:
  pgdata:
  pyenv:
