exclude        = ["venv", ".venv"]
line-length    = 100
target-version = "py311"

[lint]
    select = [
        "E", # Errors
        "F", # Pyflakes
        "I", # Isort
        "W", # Warnings about wrong format
        "T20", # Look for print() statements
    ]