# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-11 12:31
from __future__ import unicode_literals

from django.db import migrations, models
import django_ltree.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Taxonomy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', django_ltree.fields.PathField(unique=True)),
                ('name', models.TextField()),
            ],
            options={
                'ordering': ('path',),
                'abstract': False,
            },
        ),
    ]
