# Generated by Django 6.0 on 2025-12-14 13:10

import django_ltree.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Taxonomy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("path", django_ltree.fields.PathField(blank=True, null=True, unique=True)),
                ("name", models.TextField()),
            ],
            options={
                "ordering": ("path",),
                "abstract": False,
            },
        ),
    ]
