# Generated by Django 6.0 on 2025-12-21 15:41

import django.contrib.postgres.indexes
import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("taxonomy", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="taxonomy",
            managers=[
                ("t_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name="taxonomy",
            index=django.contrib.postgres.indexes.BTreeIndex(
                fields=["path"], name="taxonomy_ta_path_98acbc_btree"
            ),
        ),
        migrations.AddIndex(
            model_name="taxonomy",
            index=django.contrib.postgres.indexes.GistIndex(
                fields=["path"], name="taxonomy_ta_path_85a7ea_gist"
            ),
        ),
    ]
